apiVersion: v1
kind: ConfigMap
metadata:
  name: custommicroservices-env
  namespace: newgen
data:
  DomainUrl: "https://odmicroservices.apps.ocpintdev.lic-india.com/"
  DomainUrlNGOne: "https://ngonemicroservices.apps.ocpintdev.lic-india.com/"
  ConnectCabinetUrl: "auth/omnidocs/v1/connect"
  ImageBufferUrl: "image/omnidocs/v1/adddocumentfrombuffer"
  AddDocumentUrl: "document/omnidocs/v1/adddocument"
  DisconnectUrl: "auth/omnidocs/v1/disconnect"
  FetchDocUrl: "image/omnidocs/v1/getdocumentbuffer"
  SearchDocUrl: "document/omnidocs/v1/searchdocument"
  DeleteDocUrl: "document/omnidocs/v1/deletedocument"
  GetDocPropertyUrl: "document/omnidocs/v1/getdocumentproperty"
  UploadWIUrl: "workitem-service-context/workitem/uploadworkitem"
  SearchWIUrl: "workitem-service-context/workitem/searchworkitems"
  FetchListUrl: "workitem-service-context/workitem/fetchworklist"
  GetWIDataUrl: "workitem-service-context/workitem/getworkitem"
  SetAttributeUrl: "workitem-service-context/workitem/setattributes"
  AddFolderUrl: "folder/omnidocs/v1/addfolder"
  FolderIdForNameUrl: "folder/omnidocs/v1/getfolderidforname"
  CheckInOutUrl: "document/omnidocs/v1/checkincheckout"
  ChangeDocProperty: "document/omnidocs/v1/changedocumentproperty"
  GetDocEdmsUrl: "http://10.196.7.53:8080/NGPolicyService/ngwebres/policy/getDocument/"
  GetDataDefPropertyUrl: "metadata/omnidocs/v1/datadefproperty"
  CabinetName: "lic_csm"
  UserName: "supervisor"
  UserPassword: "System123#"
  VolumeId: "1"
  UserName1: "BAc_user"
  UserPassword1: "System123#"
  UserName2: "BAp_user"
  UserPassword2: "System123#"
  DataClassName: "Policy_Docket"
  DataDefIndex: "6"
  DataClassKeyValues: "Policy_Number#$#Branch_Code#$#Division_Code#$#Document_Type#$#Journey_Completed"
  DataClassKeyTypes: "L#$#S#$#L#$#S#$#S"
  DataClassKeyId: "28#$#29#$#30#$#31#$#32"
  Test: "ValueFromConfigMap"
  Log4jPath: "/Newgen/CustomMicroservice/NGLogs"
  BrmsJsonPath: "/Newgen/CustomMicroservice/BrmsJsonFiles"
  BrmsExecUrl: "https://ngonebrmsmicroservices.apps.ocpintdev.lic-india.com/rule-execution-service-context/brms/exec?"