FROM localhost/newgenalpine:openjdk17
LABEL maintainer="Newgen Software Technologies Limited"

COPY --chown=docker:newgen --chmod=0775 run.sh /bin/
COPY --chown=docker:newgen --chmod=0775 restartservice.sh /bin/

#AddDocument API 
COPY --chown=docker:newgen Output/Tomcat/webapps/LIC_DocumentService.jar /Newgen/

WORKDIR /Newgen/

EXPOSE 8080

#Switch to user: docker
USER 1000

CMD /bin/run.sh 
